### ISSUE TITLE
Implement UI Layout in Notebook

### ISSUE THREAD

**Issue by matthew-oberg** [cs481-ekh/s24-slice-n-dice#102]
References #89 

 - [x] Put proposed and accepted UI layout into GoVizzy notebook
 - [x] Rearrange existing widgets to fit new layout
 - [x] Add automated testing to the extent possible

**Comment by ryliewalsh** [comment]
Closed with pr #110

**Comment by ryliewalsh** [comment]
Closed with PR #110
