### ISSUE TITLE
Research UI testing

### ISSUE THREAD

**Issue by ryliewalsh** [cs481-ekh/s24-slice-n-dice#120]
References #117

**Comment by dignojrteogalbo** [comment]
Found these resources:
- [https://github.com/jupyter-widgets/ipywidgets/issues/2934](https://github.com/jupyter-widgets/ipywidgets/issues/2934)
- [https://github.com/widgetti/solara](https://github.com/widgetti/solara)
- [https://solara.dev/docs/howto/testing](https://solara.dev/docs/howto/testing)

Using Solara will cause us to switch from ipyvolume/ipywidgets to it. Doesn't seem viable at this stage of our development.

[Galata ](https://github.com/jupyterlab/jupyterlab/tree/main/galata) is the visual regression tester for ipywidgets which will require us to incorporate Javascript/Typescript.

{t:16}

**Comment by maartenbreddels** [comment]
Hi,

> Using Solara will cause us to switch from ipyvolume/ipywidgets to it

This is not the case, solara works with all widget libraries, like classic ipywidgets and ipyvolume.

Since then we split off the package from [solara](https://github.com/widgetti/solara/) and it is now called [pytest-ipywidgets](https://pypi.org/project/pytest-ipywidgets/), which allows you to test with or without a browser (playwright).

A basic example is:
```python
import ipywidgets as widgets
import playwright.sync_api
from IPython.display import display

def test_widget_button_solara(solara_test, page_session: playwright.sync_api.Page):
    # The test code runs in the same process as solara-server (which runs in a separate thread)
    # Note: this test uses ipywidgets directly, not solara components.
    button = widgets.Button(description="Click Me!")

    def change_description(obj):
        button.description = "Tested event"

    button.on_click(change_description)
    display(button)
    page_session.locator("text=Click Me!").click()
    page_session.locator("text=Tested event").wait_for()
```
