### ISSUE TITLE
Research atom visualization

### ISSUE THREAD

**Issue by ryliewalsh** [cs481-ekh/s24-slice-n-dice#129]

**Comment by dignojrteogalbo** [comment]
Referencing the ipyvolume docs:
- [https://ipyvolume.readthedocs.io/en/latest/examples/mesh.html](https://ipyvolume.readthedocs.io/en/latest/examples/mesh.html)
- [https://ipyvolume.readthedocs.io/en/latest/api.html#ipyvolume.pylab.plot_surface](https://ipyvolume.readthedocs.io/en/latest/api.html#ipyvolume.pylab.plot_surface)

My initial attempt will be to create a mesh using the `plot_surface()` API. The mesh will be created by a [parametric surface](https://en.wikipedia.org/wiki/Parametric_surface) defining the [shape of a sphere](https://www.math.purdue.edu/~neptamin/324Au17/Notes/16.6/16.6.pdf).

I think I will need to parameterize the sphere surface formula by (x, y, z) spatial coordinates and with a radius parameter.

{t:8}
