### ISSUE TITLE
Position Atom in Graph

### ISSUE THREAD

**Issue by ryliewalsh** [cs481-ekh/s24-slice-n-dice#132]
References User story #34 

- [ ] Be able to show atom at appropriate places in graph

**Comment by dignojrteogalbo** [comment]
Working on using the atoms library to utilized my sphere plotting method. Digging into `get_positions()` and [get_scaled_positions()](https://wiki.fysik.dtu.dk/ase/ase/atoms.html#ase.Atoms.get_scaled_positions).

{t:60}

**Comment by dignojrteogalbo** [comment]
Was able to get the atoms plotted in the right spots.
![image](https://github.com/cs481-ekh/s24-slice-n-dice/assets/49927429/f1e9d179-b7b1-47cc-b584-9c8d09b271ca)

{t:180}
