### ISSUE TITLE
2d slicing options

### ISSUE THREAD

**Issue by BraydenThompson** [cs481-ekh/s24-slice-n-dice#180]
References #176

Provide widgets that expose configuration options for the 2d slices, such as color, transfer function (if applicable), etc.

**Comment by matthew-oberg** [comment]
Began looking into and prototyping Matplotlib color and appearance options.

[t:60]

**Comment by matthew-oberg** [comment]
Exploring using matplotlib color map.

[t:60]

**Comment by matthew-oberg** [comment]
Implemented fully, PR put up.

[t:30]
