### ISSUE TITLE
Sketch out and propose UI layout

### ISSUE THREAD

**Issue by matthew-oberg** [cs481-ekh/s24-slice-n-dice#90]
References #89

Come up with a final layout for the UI.

 - [x] Research Jupyter Notebook UIs
 - [x] Sketch out proposed final GoVizzy UI

**Comment by ryliewalsh** [comment]
Researched and designed the layout. Debated using html but that came with a lot of complications in using it with 
Jupyter. Also considered that the end goal is to hand this off to the chem team that is learning python so that would be the preferred language.
[t:60]
