### ISSUE TITLE
Show widget on run

### ISSUE THREAD

**Issue by matthew-oberg** [cs481-ekh/s24-slice-n-dice#92]
References #26 

 - [ ] Show the visualization widget
 - [ ] Implement automated testing of widget to extent possible

**Comment by dignojrteogalbo** [comment]
Was able to create widget in a separate module and display the widget in the notebook.
![image](https://github.com/cs481-ekh/s24-slice-n-dice/assets/49927429/66bccf85-893b-4ccf-b953-dcc48df6fd2f)

{t:45}

**Comment by dignojrteogalbo** [comment]
Closed by PR #109
