### ISSUE TITLE
Display some cube file data

### ISSUE THREAD

**Issue by matthew-oberg** [cs481-ekh/s24-slice-n-dice#93]
References #26 

 - [ ] Show some data (single slice, etc.) from a cube file in the widget
 - [ ] Implement automated testing to extent possible

**Comment by dignojrteogalbo** [comment]
Got to displaying file information and cell properties in a widget from the Cube object.
![image](https://github.com/cs481-ekh/s24-slice-n-dice/assets/49927429/af5e2604-a476-496b-94c4-ded86ff941b0)

{t:80}
