### ISSUE TITLE
Display 3D point cloud of cube file

### ISSUE THREAD

**Issue by matthew-oberg** [cs481-ekh/s24-slice-n-dice#95]
References #26 

 - [ ] Show a point cloud of a full cube file in the visualization widget
 - [ ] Implement automated testing to extent possible

**Comment by dignojrteogalbo** [comment]
Working on getting the .cube volumetric data shown. Got the grid points to appear on a scatter plot.
![image](https://github.com/cs481-ekh/s24-slice-n-dice/assets/49927429/4e1f02e9-45c2-4725-b5e8-b1aa1532c55e)

{t:60}

**Comment by dignojrteogalbo** [comment]
Got the volumetric data on a widget.
![image](https://github.com/cs481-ekh/s24-slice-n-dice/assets/49927429/8aee67a0-23c4-445e-9b0b-4d899f94ecea)

{t:30}
